# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/peter/Development/beebem-macos

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/peter/Development/beebem-macos

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/peter/Development/beebem-macos/CMakeFiles /Users/peter/Development/beebem-macos//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/peter/Development/beebem-macos/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named BeebEm

# Build rule for target.
BeebEm: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 BeebEm
.PHONY : BeebEm

# fast build rule for target.
BeebEm/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/build
.PHONY : BeebEm/fast

#=============================================================================
# Target rules for targets named MetalShaders

# Build rule for target.
MetalShaders: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 MetalShaders
.PHONY : MetalShaders

# fast build rule for target.
MetalShaders/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/MetalShaders.dir/build.make CMakeFiles/MetalShaders.dir/build
.PHONY : MetalShaders/fast

src/6502core.o: src/6502core.cpp.o
.PHONY : src/6502core.o

# target to build an object file
src/6502core.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/6502core.cpp.o
.PHONY : src/6502core.cpp.o

src/6502core.i: src/6502core.cpp.i
.PHONY : src/6502core.i

# target to preprocess a source file
src/6502core.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/6502core.cpp.i
.PHONY : src/6502core.cpp.i

src/6502core.s: src/6502core.cpp.s
.PHONY : src/6502core.s

# target to generate assembly for a file
src/6502core.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/6502core.cpp.s
.PHONY : src/6502core.cpp.s

src/ARMulator/armdis.o: src/ARMulator/armdis.cpp.o
.PHONY : src/ARMulator/armdis.o

# target to build an object file
src/ARMulator/armdis.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ARMulator/armdis.cpp.o
.PHONY : src/ARMulator/armdis.cpp.o

src/ARMulator/armdis.i: src/ARMulator/armdis.cpp.i
.PHONY : src/ARMulator/armdis.i

# target to preprocess a source file
src/ARMulator/armdis.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ARMulator/armdis.cpp.i
.PHONY : src/ARMulator/armdis.cpp.i

src/ARMulator/armdis.s: src/ARMulator/armdis.cpp.s
.PHONY : src/ARMulator/armdis.s

# target to generate assembly for a file
src/ARMulator/armdis.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ARMulator/armdis.cpp.s
.PHONY : src/ARMulator/armdis.cpp.s

src/ARMulator/armemu.o: src/ARMulator/armemu.cpp.o
.PHONY : src/ARMulator/armemu.o

# target to build an object file
src/ARMulator/armemu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ARMulator/armemu.cpp.o
.PHONY : src/ARMulator/armemu.cpp.o

src/ARMulator/armemu.i: src/ARMulator/armemu.cpp.i
.PHONY : src/ARMulator/armemu.i

# target to preprocess a source file
src/ARMulator/armemu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ARMulator/armemu.cpp.i
.PHONY : src/ARMulator/armemu.cpp.i

src/ARMulator/armemu.s: src/ARMulator/armemu.cpp.s
.PHONY : src/ARMulator/armemu.s

# target to generate assembly for a file
src/ARMulator/armemu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ARMulator/armemu.cpp.s
.PHONY : src/ARMulator/armemu.cpp.s

src/ARMulator/arminit.o: src/ARMulator/arminit.cpp.o
.PHONY : src/ARMulator/arminit.o

# target to build an object file
src/ARMulator/arminit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ARMulator/arminit.cpp.o
.PHONY : src/ARMulator/arminit.cpp.o

src/ARMulator/arminit.i: src/ARMulator/arminit.cpp.i
.PHONY : src/ARMulator/arminit.i

# target to preprocess a source file
src/ARMulator/arminit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ARMulator/arminit.cpp.i
.PHONY : src/ARMulator/arminit.cpp.i

src/ARMulator/arminit.s: src/ARMulator/arminit.cpp.s
.PHONY : src/ARMulator/arminit.s

# target to generate assembly for a file
src/ARMulator/arminit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ARMulator/arminit.cpp.s
.PHONY : src/ARMulator/arminit.cpp.s

src/ARMulator/armstubs.o: src/ARMulator/armstubs.cpp.o
.PHONY : src/ARMulator/armstubs.o

# target to build an object file
src/ARMulator/armstubs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ARMulator/armstubs.cpp.o
.PHONY : src/ARMulator/armstubs.cpp.o

src/ARMulator/armstubs.i: src/ARMulator/armstubs.cpp.i
.PHONY : src/ARMulator/armstubs.i

# target to preprocess a source file
src/ARMulator/armstubs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ARMulator/armstubs.cpp.i
.PHONY : src/ARMulator/armstubs.cpp.i

src/ARMulator/armstubs.s: src/ARMulator/armstubs.cpp.s
.PHONY : src/ARMulator/armstubs.s

# target to generate assembly for a file
src/ARMulator/armstubs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ARMulator/armstubs.cpp.s
.PHONY : src/ARMulator/armstubs.cpp.s

src/ARMulator/armsupp.o: src/ARMulator/armsupp.cpp.o
.PHONY : src/ARMulator/armsupp.o

# target to build an object file
src/ARMulator/armsupp.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ARMulator/armsupp.cpp.o
.PHONY : src/ARMulator/armsupp.cpp.o

src/ARMulator/armsupp.i: src/ARMulator/armsupp.cpp.i
.PHONY : src/ARMulator/armsupp.i

# target to preprocess a source file
src/ARMulator/armsupp.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ARMulator/armsupp.cpp.i
.PHONY : src/ARMulator/armsupp.cpp.i

src/ARMulator/armsupp.s: src/ARMulator/armsupp.cpp.s
.PHONY : src/ARMulator/armsupp.s

# target to generate assembly for a file
src/ARMulator/armsupp.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ARMulator/armsupp.cpp.s
.PHONY : src/ARMulator/armsupp.cpp.s

src/ARMulator/thumbemu.o: src/ARMulator/thumbemu.cpp.o
.PHONY : src/ARMulator/thumbemu.o

# target to build an object file
src/ARMulator/thumbemu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ARMulator/thumbemu.cpp.o
.PHONY : src/ARMulator/thumbemu.cpp.o

src/ARMulator/thumbemu.i: src/ARMulator/thumbemu.cpp.i
.PHONY : src/ARMulator/thumbemu.i

# target to preprocess a source file
src/ARMulator/thumbemu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ARMulator/thumbemu.cpp.i
.PHONY : src/ARMulator/thumbemu.cpp.i

src/ARMulator/thumbemu.s: src/ARMulator/thumbemu.cpp.s
.PHONY : src/ARMulator/thumbemu.s

# target to generate assembly for a file
src/ARMulator/thumbemu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ARMulator/thumbemu.cpp.s
.PHONY : src/ARMulator/thumbemu.cpp.s

src/AppDelegate.o: src/AppDelegate.mm.o
.PHONY : src/AppDelegate.o

# target to build an object file
src/AppDelegate.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/AppDelegate.mm.o
.PHONY : src/AppDelegate.mm.o

src/Arm.o: src/Arm.cpp.o
.PHONY : src/Arm.o

# target to build an object file
src/Arm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Arm.cpp.o
.PHONY : src/Arm.cpp.o

src/Arm.i: src/Arm.cpp.i
.PHONY : src/Arm.i

# target to preprocess a source file
src/Arm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Arm.cpp.i
.PHONY : src/Arm.cpp.i

src/Arm.s: src/Arm.cpp.s
.PHONY : src/Arm.s

# target to generate assembly for a file
src/Arm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Arm.cpp.s
.PHONY : src/Arm.cpp.s

src/ArmDisassembler.o: src/ArmDisassembler.cpp.o
.PHONY : src/ArmDisassembler.o

# target to build an object file
src/ArmDisassembler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ArmDisassembler.cpp.o
.PHONY : src/ArmDisassembler.cpp.o

src/ArmDisassembler.i: src/ArmDisassembler.cpp.i
.PHONY : src/ArmDisassembler.i

# target to preprocess a source file
src/ArmDisassembler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ArmDisassembler.cpp.i
.PHONY : src/ArmDisassembler.cpp.i

src/ArmDisassembler.s: src/ArmDisassembler.cpp.s
.PHONY : src/ArmDisassembler.s

# target to generate assembly for a file
src/ArmDisassembler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ArmDisassembler.cpp.s
.PHONY : src/ArmDisassembler.cpp.s

src/AtoDConv.o: src/AtoDConv.cpp.o
.PHONY : src/AtoDConv.o

# target to build an object file
src/AtoDConv.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/AtoDConv.cpp.o
.PHONY : src/AtoDConv.cpp.o

src/AtoDConv.i: src/AtoDConv.cpp.i
.PHONY : src/AtoDConv.i

# target to preprocess a source file
src/AtoDConv.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/AtoDConv.cpp.i
.PHONY : src/AtoDConv.cpp.i

src/AtoDConv.s: src/AtoDConv.cpp.s
.PHONY : src/AtoDConv.s

# target to generate assembly for a file
src/AtoDConv.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/AtoDConv.cpp.s
.PHONY : src/AtoDConv.cpp.s

src/AviWriter.o: src/AviWriter.cpp.o
.PHONY : src/AviWriter.o

# target to build an object file
src/AviWriter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/AviWriter.cpp.o
.PHONY : src/AviWriter.cpp.o

src/AviWriter.i: src/AviWriter.cpp.i
.PHONY : src/AviWriter.i

# target to preprocess a source file
src/AviWriter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/AviWriter.cpp.i
.PHONY : src/AviWriter.cpp.i

src/AviWriter.s: src/AviWriter.cpp.s
.PHONY : src/AviWriter.s

# target to generate assembly for a file
src/AviWriter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/AviWriter.cpp.s
.PHONY : src/AviWriter.cpp.s

src/Bcd.o: src/Bcd.cpp.o
.PHONY : src/Bcd.o

# target to build an object file
src/Bcd.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Bcd.cpp.o
.PHONY : src/Bcd.cpp.o

src/Bcd.i: src/Bcd.cpp.i
.PHONY : src/Bcd.i

# target to preprocess a source file
src/Bcd.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Bcd.cpp.i
.PHONY : src/Bcd.cpp.i

src/Bcd.s: src/Bcd.cpp.s
.PHONY : src/Bcd.s

# target to generate assembly for a file
src/Bcd.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Bcd.cpp.s
.PHONY : src/Bcd.cpp.s

src/BeebMem.o: src/BeebMem.cpp.o
.PHONY : src/BeebMem.o

# target to build an object file
src/BeebMem.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/BeebMem.cpp.o
.PHONY : src/BeebMem.cpp.o

src/BeebMem.i: src/BeebMem.cpp.i
.PHONY : src/BeebMem.i

# target to preprocess a source file
src/BeebMem.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/BeebMem.cpp.i
.PHONY : src/BeebMem.cpp.i

src/BeebMem.s: src/BeebMem.cpp.s
.PHONY : src/BeebMem.s

# target to generate assembly for a file
src/BeebMem.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/BeebMem.cpp.s
.PHONY : src/BeebMem.cpp.s

src/BeebMetalView.o: src/BeebMetalView.mm.o
.PHONY : src/BeebMetalView.o

# target to build an object file
src/BeebMetalView.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/BeebMetalView.mm.o
.PHONY : src/BeebMetalView.mm.o

src/BeebRenderer.o: src/BeebRenderer.mm.o
.PHONY : src/BeebRenderer.o

# target to build an object file
src/BeebRenderer.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/BeebRenderer.mm.o
.PHONY : src/BeebRenderer.mm.o

src/BeebWin.o: src/BeebWin.cpp.o
.PHONY : src/BeebWin.o

# target to build an object file
src/BeebWin.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/BeebWin.cpp.o
.PHONY : src/BeebWin.cpp.o

src/BeebWin.i: src/BeebWin.cpp.i
.PHONY : src/BeebWin.i

# target to preprocess a source file
src/BeebWin.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/BeebWin.cpp.i
.PHONY : src/BeebWin.cpp.i

src/BeebWin.s: src/BeebWin.cpp.s
.PHONY : src/BeebWin.s

# target to generate assembly for a file
src/BeebWin.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/BeebWin.cpp.s
.PHONY : src/BeebWin.cpp.s

src/BeebWinDx.o: src/BeebWinDx.cpp.o
.PHONY : src/BeebWinDx.o

# target to build an object file
src/BeebWinDx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/BeebWinDx.cpp.o
.PHONY : src/BeebWinDx.cpp.o

src/BeebWinDx.i: src/BeebWinDx.cpp.i
.PHONY : src/BeebWinDx.i

# target to preprocess a source file
src/BeebWinDx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/BeebWinDx.cpp.i
.PHONY : src/BeebWinDx.cpp.i

src/BeebWinDx.s: src/BeebWinDx.cpp.s
.PHONY : src/BeebWinDx.s

# target to generate assembly for a file
src/BeebWinDx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/BeebWinDx.cpp.s
.PHONY : src/BeebWinDx.cpp.s

src/BeebWinIo.o: src/BeebWinIo.cpp.o
.PHONY : src/BeebWinIo.o

# target to build an object file
src/BeebWinIo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/BeebWinIo.cpp.o
.PHONY : src/BeebWinIo.cpp.o

src/BeebWinIo.i: src/BeebWinIo.cpp.i
.PHONY : src/BeebWinIo.i

# target to preprocess a source file
src/BeebWinIo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/BeebWinIo.cpp.i
.PHONY : src/BeebWinIo.cpp.i

src/BeebWinIo.s: src/BeebWinIo.cpp.s
.PHONY : src/BeebWinIo.s

# target to generate assembly for a file
src/BeebWinIo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/BeebWinIo.cpp.s
.PHONY : src/BeebWinIo.cpp.s

src/BeebWinPrefs.o: src/BeebWinPrefs.cpp.o
.PHONY : src/BeebWinPrefs.o

# target to build an object file
src/BeebWinPrefs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/BeebWinPrefs.cpp.o
.PHONY : src/BeebWinPrefs.cpp.o

src/BeebWinPrefs.i: src/BeebWinPrefs.cpp.i
.PHONY : src/BeebWinPrefs.i

# target to preprocess a source file
src/BeebWinPrefs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/BeebWinPrefs.cpp.i
.PHONY : src/BeebWinPrefs.cpp.i

src/BeebWinPrefs.s: src/BeebWinPrefs.cpp.s
.PHONY : src/BeebWinPrefs.s

# target to generate assembly for a file
src/BeebWinPrefs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/BeebWinPrefs.cpp.s
.PHONY : src/BeebWinPrefs.cpp.s

src/BeebWinSpeech.o: src/BeebWinSpeech.cpp.o
.PHONY : src/BeebWinSpeech.o

# target to build an object file
src/BeebWinSpeech.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/BeebWinSpeech.cpp.o
.PHONY : src/BeebWinSpeech.cpp.o

src/BeebWinSpeech.i: src/BeebWinSpeech.cpp.i
.PHONY : src/BeebWinSpeech.i

# target to preprocess a source file
src/BeebWinSpeech.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/BeebWinSpeech.cpp.i
.PHONY : src/BeebWinSpeech.cpp.i

src/BeebWinSpeech.s: src/BeebWinSpeech.cpp.s
.PHONY : src/BeebWinSpeech.s

# target to generate assembly for a file
src/BeebWinSpeech.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/BeebWinSpeech.cpp.s
.PHONY : src/BeebWinSpeech.cpp.s

src/ComboBox.o: src/ComboBox.cpp.o
.PHONY : src/ComboBox.o

# target to build an object file
src/ComboBox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ComboBox.cpp.o
.PHONY : src/ComboBox.cpp.o

src/ComboBox.i: src/ComboBox.cpp.i
.PHONY : src/ComboBox.i

# target to preprocess a source file
src/ComboBox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ComboBox.cpp.i
.PHONY : src/ComboBox.cpp.i

src/ComboBox.s: src/ComboBox.cpp.s
.PHONY : src/ComboBox.s

# target to generate assembly for a file
src/ComboBox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ComboBox.cpp.s
.PHONY : src/ComboBox.cpp.s

src/CoreAudioStreamer.o: src/CoreAudioStreamer.mm.o
.PHONY : src/CoreAudioStreamer.o

# target to build an object file
src/CoreAudioStreamer.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/CoreAudioStreamer.mm.o
.PHONY : src/CoreAudioStreamer.mm.o

src/Csw.o: src/Csw.cpp.o
.PHONY : src/Csw.o

# target to build an object file
src/Csw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Csw.cpp.o
.PHONY : src/Csw.cpp.o

src/Csw.i: src/Csw.cpp.i
.PHONY : src/Csw.i

# target to preprocess a source file
src/Csw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Csw.cpp.i
.PHONY : src/Csw.cpp.i

src/Csw.s: src/Csw.cpp.s
.PHONY : src/Csw.s

# target to generate assembly for a file
src/Csw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Csw.cpp.s
.PHONY : src/Csw.cpp.s

src/Debug.o: src/Debug.cpp.o
.PHONY : src/Debug.o

# target to build an object file
src/Debug.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Debug.cpp.o
.PHONY : src/Debug.cpp.o

src/Debug.i: src/Debug.cpp.i
.PHONY : src/Debug.i

# target to preprocess a source file
src/Debug.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Debug.cpp.i
.PHONY : src/Debug.cpp.i

src/Debug.s: src/Debug.cpp.s
.PHONY : src/Debug.s

# target to generate assembly for a file
src/Debug.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Debug.cpp.s
.PHONY : src/Debug.cpp.s

src/DebugTrace.o: src/DebugTrace.cpp.o
.PHONY : src/DebugTrace.o

# target to build an object file
src/DebugTrace.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/DebugTrace.cpp.o
.PHONY : src/DebugTrace.cpp.o

src/DebugTrace.i: src/DebugTrace.cpp.i
.PHONY : src/DebugTrace.i

# target to preprocess a source file
src/DebugTrace.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/DebugTrace.cpp.i
.PHONY : src/DebugTrace.cpp.i

src/DebugTrace.s: src/DebugTrace.cpp.s
.PHONY : src/DebugTrace.s

# target to generate assembly for a file
src/DebugTrace.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/DebugTrace.cpp.s
.PHONY : src/DebugTrace.cpp.s

src/Dialog.o: src/Dialog.cpp.o
.PHONY : src/Dialog.o

# target to build an object file
src/Dialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Dialog.cpp.o
.PHONY : src/Dialog.cpp.o

src/Dialog.i: src/Dialog.cpp.i
.PHONY : src/Dialog.i

# target to preprocess a source file
src/Dialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Dialog.cpp.i
.PHONY : src/Dialog.cpp.i

src/Dialog.s: src/Dialog.cpp.s
.PHONY : src/Dialog.s

# target to generate assembly for a file
src/Dialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Dialog.cpp.s
.PHONY : src/Dialog.cpp.s

src/Disc1770.o: src/Disc1770.cpp.o
.PHONY : src/Disc1770.o

# target to build an object file
src/Disc1770.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Disc1770.cpp.o
.PHONY : src/Disc1770.cpp.o

src/Disc1770.i: src/Disc1770.cpp.i
.PHONY : src/Disc1770.i

# target to preprocess a source file
src/Disc1770.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Disc1770.cpp.i
.PHONY : src/Disc1770.cpp.i

src/Disc1770.s: src/Disc1770.cpp.s
.PHONY : src/Disc1770.s

# target to generate assembly for a file
src/Disc1770.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Disc1770.cpp.s
.PHONY : src/Disc1770.cpp.s

src/Disc8271.o: src/Disc8271.cpp.o
.PHONY : src/Disc8271.o

# target to build an object file
src/Disc8271.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Disc8271.cpp.o
.PHONY : src/Disc8271.cpp.o

src/Disc8271.i: src/Disc8271.cpp.i
.PHONY : src/Disc8271.i

# target to preprocess a source file
src/Disc8271.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Disc8271.cpp.i
.PHONY : src/Disc8271.cpp.i

src/Disc8271.s: src/Disc8271.cpp.s
.PHONY : src/Disc8271.s

# target to generate assembly for a file
src/Disc8271.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Disc8271.cpp.s
.PHONY : src/Disc8271.cpp.s

src/DiscEdit.o: src/DiscEdit.cpp.o
.PHONY : src/DiscEdit.o

# target to build an object file
src/DiscEdit.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/DiscEdit.cpp.o
.PHONY : src/DiscEdit.cpp.o

src/DiscEdit.i: src/DiscEdit.cpp.i
.PHONY : src/DiscEdit.i

# target to preprocess a source file
src/DiscEdit.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/DiscEdit.cpp.i
.PHONY : src/DiscEdit.cpp.i

src/DiscEdit.s: src/DiscEdit.cpp.s
.PHONY : src/DiscEdit.s

# target to generate assembly for a file
src/DiscEdit.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/DiscEdit.cpp.s
.PHONY : src/DiscEdit.cpp.s

src/DiscInfo.o: src/DiscInfo.cpp.o
.PHONY : src/DiscInfo.o

# target to build an object file
src/DiscInfo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/DiscInfo.cpp.o
.PHONY : src/DiscInfo.cpp.o

src/DiscInfo.i: src/DiscInfo.cpp.i
.PHONY : src/DiscInfo.i

# target to preprocess a source file
src/DiscInfo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/DiscInfo.cpp.i
.PHONY : src/DiscInfo.cpp.i

src/DiscInfo.s: src/DiscInfo.cpp.s
.PHONY : src/DiscInfo.s

# target to generate assembly for a file
src/DiscInfo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/DiscInfo.cpp.s
.PHONY : src/DiscInfo.cpp.s

src/Econet.o: src/Econet.cpp.o
.PHONY : src/Econet.o

# target to build an object file
src/Econet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Econet.cpp.o
.PHONY : src/Econet.cpp.o

src/Econet.i: src/Econet.cpp.i
.PHONY : src/Econet.i

# target to preprocess a source file
src/Econet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Econet.cpp.i
.PHONY : src/Econet.cpp.i

src/Econet.s: src/Econet.cpp.s
.PHONY : src/Econet.s

# target to generate assembly for a file
src/Econet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Econet.cpp.s
.PHONY : src/Econet.cpp.s

src/Ext1770.o: src/Ext1770.cpp.o
.PHONY : src/Ext1770.o

# target to build an object file
src/Ext1770.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Ext1770.cpp.o
.PHONY : src/Ext1770.cpp.o

src/Ext1770.i: src/Ext1770.cpp.i
.PHONY : src/Ext1770.i

# target to preprocess a source file
src/Ext1770.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Ext1770.cpp.i
.PHONY : src/Ext1770.cpp.i

src/Ext1770.s: src/Ext1770.cpp.s
.PHONY : src/Ext1770.s

# target to generate assembly for a file
src/Ext1770.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Ext1770.cpp.s
.PHONY : src/Ext1770.cpp.s

src/FileType.o: src/FileType.cpp.o
.PHONY : src/FileType.o

# target to build an object file
src/FileType.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/FileType.cpp.o
.PHONY : src/FileType.cpp.o

src/FileType.i: src/FileType.cpp.i
.PHONY : src/FileType.i

# target to preprocess a source file
src/FileType.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/FileType.cpp.i
.PHONY : src/FileType.cpp.i

src/FileType.s: src/FileType.cpp.s
.PHONY : src/FileType.s

# target to generate assembly for a file
src/FileType.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/FileType.cpp.s
.PHONY : src/FileType.cpp.s

src/FileUtils.o: src/FileUtils.cpp.o
.PHONY : src/FileUtils.o

# target to build an object file
src/FileUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/FileUtils.cpp.o
.PHONY : src/FileUtils.cpp.o

src/FileUtils.i: src/FileUtils.cpp.i
.PHONY : src/FileUtils.i

# target to preprocess a source file
src/FileUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/FileUtils.cpp.i
.PHONY : src/FileUtils.cpp.i

src/FileUtils.s: src/FileUtils.cpp.s
.PHONY : src/FileUtils.s

# target to generate assembly for a file
src/FileUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/FileUtils.cpp.s
.PHONY : src/FileUtils.cpp.s

src/Hardware/Acorn1770/Acorn.o: src/Hardware/Acorn1770/Acorn.cpp.o
.PHONY : src/Hardware/Acorn1770/Acorn.o

# target to build an object file
src/Hardware/Acorn1770/Acorn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Hardware/Acorn1770/Acorn.cpp.o
.PHONY : src/Hardware/Acorn1770/Acorn.cpp.o

src/Hardware/Acorn1770/Acorn.i: src/Hardware/Acorn1770/Acorn.cpp.i
.PHONY : src/Hardware/Acorn1770/Acorn.i

# target to preprocess a source file
src/Hardware/Acorn1770/Acorn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Hardware/Acorn1770/Acorn.cpp.i
.PHONY : src/Hardware/Acorn1770/Acorn.cpp.i

src/Hardware/Acorn1770/Acorn.s: src/Hardware/Acorn1770/Acorn.cpp.s
.PHONY : src/Hardware/Acorn1770/Acorn.s

# target to generate assembly for a file
src/Hardware/Acorn1770/Acorn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Hardware/Acorn1770/Acorn.cpp.s
.PHONY : src/Hardware/Acorn1770/Acorn.cpp.s

src/Hardware/OpusDDOS/Opus.o: src/Hardware/OpusDDOS/Opus.cpp.o
.PHONY : src/Hardware/OpusDDOS/Opus.o

# target to build an object file
src/Hardware/OpusDDOS/Opus.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Hardware/OpusDDOS/Opus.cpp.o
.PHONY : src/Hardware/OpusDDOS/Opus.cpp.o

src/Hardware/OpusDDOS/Opus.i: src/Hardware/OpusDDOS/Opus.cpp.i
.PHONY : src/Hardware/OpusDDOS/Opus.i

# target to preprocess a source file
src/Hardware/OpusDDOS/Opus.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Hardware/OpusDDOS/Opus.cpp.i
.PHONY : src/Hardware/OpusDDOS/Opus.cpp.i

src/Hardware/OpusDDOS/Opus.s: src/Hardware/OpusDDOS/Opus.cpp.s
.PHONY : src/Hardware/OpusDDOS/Opus.s

# target to generate assembly for a file
src/Hardware/OpusDDOS/Opus.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Hardware/OpusDDOS/Opus.cpp.s
.PHONY : src/Hardware/OpusDDOS/Opus.cpp.s

src/Hardware/Watford/Watford.o: src/Hardware/Watford/Watford.cpp.o
.PHONY : src/Hardware/Watford/Watford.o

# target to build an object file
src/Hardware/Watford/Watford.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Hardware/Watford/Watford.cpp.o
.PHONY : src/Hardware/Watford/Watford.cpp.o

src/Hardware/Watford/Watford.i: src/Hardware/Watford/Watford.cpp.i
.PHONY : src/Hardware/Watford/Watford.i

# target to preprocess a source file
src/Hardware/Watford/Watford.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Hardware/Watford/Watford.cpp.i
.PHONY : src/Hardware/Watford/Watford.cpp.i

src/Hardware/Watford/Watford.s: src/Hardware/Watford/Watford.cpp.s
.PHONY : src/Hardware/Watford/Watford.s

# target to generate assembly for a file
src/Hardware/Watford/Watford.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Hardware/Watford/Watford.cpp.s
.PHONY : src/Hardware/Watford/Watford.cpp.s

src/IC32Latch.o: src/IC32Latch.cpp.o
.PHONY : src/IC32Latch.o

# target to build an object file
src/IC32Latch.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/IC32Latch.cpp.o
.PHONY : src/IC32Latch.cpp.o

src/IC32Latch.i: src/IC32Latch.cpp.i
.PHONY : src/IC32Latch.i

# target to preprocess a source file
src/IC32Latch.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/IC32Latch.cpp.i
.PHONY : src/IC32Latch.cpp.i

src/IC32Latch.s: src/IC32Latch.cpp.s
.PHONY : src/IC32Latch.s

# target to generate assembly for a file
src/IC32Latch.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/IC32Latch.cpp.s
.PHONY : src/IC32Latch.cpp.s

src/IP232.o: src/IP232.cpp.o
.PHONY : src/IP232.o

# target to build an object file
src/IP232.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/IP232.cpp.o
.PHONY : src/IP232.cpp.o

src/IP232.i: src/IP232.cpp.i
.PHONY : src/IP232.i

# target to preprocess a source file
src/IP232.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/IP232.cpp.i
.PHONY : src/IP232.cpp.i

src/IP232.s: src/IP232.cpp.s
.PHONY : src/IP232.s

# target to generate assembly for a file
src/IP232.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/IP232.cpp.s
.PHONY : src/IP232.cpp.s

src/Ide.o: src/Ide.cpp.o
.PHONY : src/Ide.o

# target to build an object file
src/Ide.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Ide.cpp.o
.PHONY : src/Ide.cpp.o

src/Ide.i: src/Ide.cpp.i
.PHONY : src/Ide.i

# target to preprocess a source file
src/Ide.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Ide.cpp.i
.PHONY : src/Ide.cpp.i

src/Ide.s: src/Ide.cpp.s
.PHONY : src/Ide.s

# target to generate assembly for a file
src/Ide.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Ide.cpp.s
.PHONY : src/Ide.cpp.s

src/JoystickController.o: src/JoystickController.cpp.o
.PHONY : src/JoystickController.o

# target to build an object file
src/JoystickController.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/JoystickController.cpp.o
.PHONY : src/JoystickController.cpp.o

src/JoystickController.i: src/JoystickController.cpp.i
.PHONY : src/JoystickController.i

# target to preprocess a source file
src/JoystickController.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/JoystickController.cpp.i
.PHONY : src/JoystickController.cpp.i

src/JoystickController.s: src/JoystickController.cpp.s
.PHONY : src/JoystickController.s

# target to generate assembly for a file
src/JoystickController.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/JoystickController.cpp.s
.PHONY : src/JoystickController.cpp.s

src/JoystickDialog.o: src/JoystickDialog.cpp.o
.PHONY : src/JoystickDialog.o

# target to build an object file
src/JoystickDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/JoystickDialog.cpp.o
.PHONY : src/JoystickDialog.cpp.o

src/JoystickDialog.i: src/JoystickDialog.cpp.i
.PHONY : src/JoystickDialog.i

# target to preprocess a source file
src/JoystickDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/JoystickDialog.cpp.i
.PHONY : src/JoystickDialog.cpp.i

src/JoystickDialog.s: src/JoystickDialog.cpp.s
.PHONY : src/JoystickDialog.s

# target to generate assembly for a file
src/JoystickDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/JoystickDialog.cpp.s
.PHONY : src/JoystickDialog.cpp.s

src/JoystickOptions.o: src/JoystickOptions.cpp.o
.PHONY : src/JoystickOptions.o

# target to build an object file
src/JoystickOptions.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/JoystickOptions.cpp.o
.PHONY : src/JoystickOptions.cpp.o

src/JoystickOptions.i: src/JoystickOptions.cpp.i
.PHONY : src/JoystickOptions.i

# target to preprocess a source file
src/JoystickOptions.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/JoystickOptions.cpp.i
.PHONY : src/JoystickOptions.cpp.i

src/JoystickOptions.s: src/JoystickOptions.cpp.s
.PHONY : src/JoystickOptions.s

# target to generate assembly for a file
src/JoystickOptions.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/JoystickOptions.cpp.s
.PHONY : src/JoystickOptions.cpp.s

src/KeyMap.o: src/KeyMap.cpp.o
.PHONY : src/KeyMap.o

# target to build an object file
src/KeyMap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/KeyMap.cpp.o
.PHONY : src/KeyMap.cpp.o

src/KeyMap.i: src/KeyMap.cpp.i
.PHONY : src/KeyMap.i

# target to preprocess a source file
src/KeyMap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/KeyMap.cpp.i
.PHONY : src/KeyMap.cpp.i

src/KeyMap.s: src/KeyMap.cpp.s
.PHONY : src/KeyMap.s

# target to generate assembly for a file
src/KeyMap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/KeyMap.cpp.s
.PHONY : src/KeyMap.cpp.s

src/KeyboardLinksDialog.o: src/KeyboardLinksDialog.cpp.o
.PHONY : src/KeyboardLinksDialog.o

# target to build an object file
src/KeyboardLinksDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/KeyboardLinksDialog.cpp.o
.PHONY : src/KeyboardLinksDialog.cpp.o

src/KeyboardLinksDialog.i: src/KeyboardLinksDialog.cpp.i
.PHONY : src/KeyboardLinksDialog.i

# target to preprocess a source file
src/KeyboardLinksDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/KeyboardLinksDialog.cpp.i
.PHONY : src/KeyboardLinksDialog.cpp.i

src/KeyboardLinksDialog.s: src/KeyboardLinksDialog.cpp.s
.PHONY : src/KeyboardLinksDialog.s

# target to generate assembly for a file
src/KeyboardLinksDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/KeyboardLinksDialog.cpp.s
.PHONY : src/KeyboardLinksDialog.cpp.s

src/ListView.o: src/ListView.cpp.o
.PHONY : src/ListView.o

# target to build an object file
src/ListView.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ListView.cpp.o
.PHONY : src/ListView.cpp.o

src/ListView.i: src/ListView.cpp.i
.PHONY : src/ListView.i

# target to preprocess a source file
src/ListView.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ListView.cpp.i
.PHONY : src/ListView.cpp.i

src/ListView.s: src/ListView.cpp.s
.PHONY : src/ListView.s

# target to generate assembly for a file
src/ListView.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/ListView.cpp.s
.PHONY : src/ListView.cpp.s

src/Log.o: src/Log.cpp.o
.PHONY : src/Log.o

# target to build an object file
src/Log.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Log.cpp.o
.PHONY : src/Log.cpp.o

src/Log.i: src/Log.cpp.i
.PHONY : src/Log.i

# target to preprocess a source file
src/Log.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Log.cpp.i
.PHONY : src/Log.cpp.i

src/Log.s: src/Log.cpp.s
.PHONY : src/Log.s

# target to generate assembly for a file
src/Log.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Log.cpp.s
.PHONY : src/Log.cpp.s

src/Master512CoPro.o: src/Master512CoPro.cpp.o
.PHONY : src/Master512CoPro.o

# target to build an object file
src/Master512CoPro.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Master512CoPro.cpp.o
.PHONY : src/Master512CoPro.cpp.o

src/Master512CoPro.i: src/Master512CoPro.cpp.i
.PHONY : src/Master512CoPro.i

# target to preprocess a source file
src/Master512CoPro.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Master512CoPro.cpp.i
.PHONY : src/Master512CoPro.cpp.i

src/Master512CoPro.s: src/Master512CoPro.cpp.s
.PHONY : src/Master512CoPro.s

# target to generate assembly for a file
src/Master512CoPro.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Master512CoPro.cpp.s
.PHONY : src/Master512CoPro.cpp.s

src/Model.o: src/Model.cpp.o
.PHONY : src/Model.o

# target to build an object file
src/Model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Model.cpp.o
.PHONY : src/Model.cpp.o

src/Model.i: src/Model.cpp.i
.PHONY : src/Model.i

# target to preprocess a source file
src/Model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Model.cpp.i
.PHONY : src/Model.cpp.i

src/Model.s: src/Model.cpp.s
.PHONY : src/Model.s

# target to generate assembly for a file
src/Model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Model.cpp.s
.PHONY : src/Model.cpp.s

src/Music5000.o: src/Music5000.cpp.o
.PHONY : src/Music5000.o

# target to build an object file
src/Music5000.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Music5000.cpp.o
.PHONY : src/Music5000.cpp.o

src/Music5000.i: src/Music5000.cpp.i
.PHONY : src/Music5000.i

# target to preprocess a source file
src/Music5000.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Music5000.cpp.i
.PHONY : src/Music5000.cpp.i

src/Music5000.s: src/Music5000.cpp.s
.PHONY : src/Music5000.s

# target to generate assembly for a file
src/Music5000.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Music5000.cpp.s
.PHONY : src/Music5000.cpp.s

src/PALRom.o: src/PALRom.cpp.o
.PHONY : src/PALRom.o

# target to build an object file
src/PALRom.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/PALRom.cpp.o
.PHONY : src/PALRom.cpp.o

src/PALRom.i: src/PALRom.cpp.i
.PHONY : src/PALRom.i

# target to preprocess a source file
src/PALRom.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/PALRom.cpp.i
.PHONY : src/PALRom.cpp.i

src/PALRom.s: src/PALRom.cpp.s
.PHONY : src/PALRom.s

# target to generate assembly for a file
src/PALRom.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/PALRom.cpp.s
.PHONY : src/PALRom.cpp.s

src/Preferences.o: src/Preferences.cpp.o
.PHONY : src/Preferences.o

# target to build an object file
src/Preferences.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Preferences.cpp.o
.PHONY : src/Preferences.cpp.o

src/Preferences.i: src/Preferences.cpp.i
.PHONY : src/Preferences.i

# target to preprocess a source file
src/Preferences.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Preferences.cpp.i
.PHONY : src/Preferences.cpp.i

src/Preferences.s: src/Preferences.cpp.s
.PHONY : src/Preferences.s

# target to generate assembly for a file
src/Preferences.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Preferences.cpp.s
.PHONY : src/Preferences.cpp.s

src/RingBuffer.o: src/RingBuffer.cpp.o
.PHONY : src/RingBuffer.o

# target to build an object file
src/RingBuffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/RingBuffer.cpp.o
.PHONY : src/RingBuffer.cpp.o

src/RingBuffer.i: src/RingBuffer.cpp.i
.PHONY : src/RingBuffer.i

# target to preprocess a source file
src/RingBuffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/RingBuffer.cpp.i
.PHONY : src/RingBuffer.cpp.i

src/RingBuffer.s: src/RingBuffer.cpp.s
.PHONY : src/RingBuffer.s

# target to generate assembly for a file
src/RingBuffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/RingBuffer.cpp.s
.PHONY : src/RingBuffer.cpp.s

src/RomConfigFile.o: src/RomConfigFile.cpp.o
.PHONY : src/RomConfigFile.o

# target to build an object file
src/RomConfigFile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/RomConfigFile.cpp.o
.PHONY : src/RomConfigFile.cpp.o

src/RomConfigFile.i: src/RomConfigFile.cpp.i
.PHONY : src/RomConfigFile.i

# target to preprocess a source file
src/RomConfigFile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/RomConfigFile.cpp.i
.PHONY : src/RomConfigFile.cpp.i

src/RomConfigFile.s: src/RomConfigFile.cpp.s
.PHONY : src/RomConfigFile.s

# target to generate assembly for a file
src/RomConfigFile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/RomConfigFile.cpp.s
.PHONY : src/RomConfigFile.cpp.s

src/Rtc.o: src/Rtc.cpp.o
.PHONY : src/Rtc.o

# target to build an object file
src/Rtc.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Rtc.cpp.o
.PHONY : src/Rtc.cpp.o

src/Rtc.i: src/Rtc.cpp.i
.PHONY : src/Rtc.i

# target to preprocess a source file
src/Rtc.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Rtc.cpp.i
.PHONY : src/Rtc.cpp.i

src/Rtc.s: src/Rtc.cpp.s
.PHONY : src/Rtc.s

# target to generate assembly for a file
src/Rtc.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Rtc.cpp.s
.PHONY : src/Rtc.cpp.s

src/Sasi.o: src/Sasi.cpp.o
.PHONY : src/Sasi.o

# target to build an object file
src/Sasi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Sasi.cpp.o
.PHONY : src/Sasi.cpp.o

src/Sasi.i: src/Sasi.cpp.i
.PHONY : src/Sasi.i

# target to preprocess a source file
src/Sasi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Sasi.cpp.i
.PHONY : src/Sasi.cpp.i

src/Sasi.s: src/Sasi.cpp.s
.PHONY : src/Sasi.s

# target to generate assembly for a file
src/Sasi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Sasi.cpp.s
.PHONY : src/Sasi.cpp.s

src/Scsi.o: src/Scsi.cpp.o
.PHONY : src/Scsi.o

# target to build an object file
src/Scsi.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Scsi.cpp.o
.PHONY : src/Scsi.cpp.o

src/Scsi.i: src/Scsi.cpp.i
.PHONY : src/Scsi.i

# target to preprocess a source file
src/Scsi.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Scsi.cpp.i
.PHONY : src/Scsi.cpp.i

src/Scsi.s: src/Scsi.cpp.s
.PHONY : src/Scsi.s

# target to generate assembly for a file
src/Scsi.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Scsi.cpp.s
.PHONY : src/Scsi.cpp.s

src/Serial.o: src/Serial.cpp.o
.PHONY : src/Serial.o

# target to build an object file
src/Serial.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Serial.cpp.o
.PHONY : src/Serial.cpp.o

src/Serial.i: src/Serial.cpp.i
.PHONY : src/Serial.i

# target to preprocess a source file
src/Serial.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Serial.cpp.i
.PHONY : src/Serial.cpp.i

src/Serial.s: src/Serial.cpp.s
.PHONY : src/Serial.s

# target to generate assembly for a file
src/Serial.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Serial.cpp.s
.PHONY : src/Serial.cpp.s

src/SerialPort.o: src/SerialPort.cpp.o
.PHONY : src/SerialPort.o

# target to build an object file
src/SerialPort.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/SerialPort.cpp.o
.PHONY : src/SerialPort.cpp.o

src/SerialPort.i: src/SerialPort.cpp.i
.PHONY : src/SerialPort.i

# target to preprocess a source file
src/SerialPort.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/SerialPort.cpp.i
.PHONY : src/SerialPort.cpp.i

src/SerialPort.s: src/SerialPort.cpp.s
.PHONY : src/SerialPort.s

# target to generate assembly for a file
src/SerialPort.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/SerialPort.cpp.s
.PHONY : src/SerialPort.cpp.s

src/Socket.o: src/Socket.cpp.o
.PHONY : src/Socket.o

# target to build an object file
src/Socket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Socket.cpp.o
.PHONY : src/Socket.cpp.o

src/Socket.i: src/Socket.cpp.i
.PHONY : src/Socket.i

# target to preprocess a source file
src/Socket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Socket.cpp.i
.PHONY : src/Socket.cpp.i

src/Socket.s: src/Socket.cpp.s
.PHONY : src/Socket.s

# target to generate assembly for a file
src/Socket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Socket.cpp.s
.PHONY : src/Socket.cpp.s

src/Sound.o: src/Sound.cpp.o
.PHONY : src/Sound.o

# target to build an object file
src/Sound.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Sound.cpp.o
.PHONY : src/Sound.cpp.o

src/Sound.i: src/Sound.cpp.i
.PHONY : src/Sound.i

# target to preprocess a source file
src/Sound.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Sound.cpp.i
.PHONY : src/Sound.cpp.i

src/Sound.s: src/Sound.cpp.s
.PHONY : src/Sound.s

# target to generate assembly for a file
src/Sound.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Sound.cpp.s
.PHONY : src/Sound.cpp.s

src/SoundStreamer.o: src/SoundStreamer.cpp.o
.PHONY : src/SoundStreamer.o

# target to build an object file
src/SoundStreamer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/SoundStreamer.cpp.o
.PHONY : src/SoundStreamer.cpp.o

src/SoundStreamer.i: src/SoundStreamer.cpp.i
.PHONY : src/SoundStreamer.i

# target to preprocess a source file
src/SoundStreamer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/SoundStreamer.cpp.i
.PHONY : src/SoundStreamer.cpp.i

src/SoundStreamer.s: src/SoundStreamer.cpp.s
.PHONY : src/SoundStreamer.s

# target to generate assembly for a file
src/SoundStreamer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/SoundStreamer.cpp.s
.PHONY : src/SoundStreamer.cpp.s

src/Speech.o: src/Speech.cpp.o
.PHONY : src/Speech.o

# target to build an object file
src/Speech.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Speech.cpp.o
.PHONY : src/Speech.cpp.o

src/Speech.i: src/Speech.cpp.i
.PHONY : src/Speech.i

# target to preprocess a source file
src/Speech.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Speech.cpp.i
.PHONY : src/Speech.cpp.i

src/Speech.s: src/Speech.cpp.s
.PHONY : src/Speech.s

# target to generate assembly for a file
src/Speech.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Speech.cpp.s
.PHONY : src/Speech.cpp.s

src/SprowCoPro.o: src/SprowCoPro.cpp.o
.PHONY : src/SprowCoPro.o

# target to build an object file
src/SprowCoPro.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/SprowCoPro.cpp.o
.PHONY : src/SprowCoPro.cpp.o

src/SprowCoPro.i: src/SprowCoPro.cpp.i
.PHONY : src/SprowCoPro.i

# target to preprocess a source file
src/SprowCoPro.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/SprowCoPro.cpp.i
.PHONY : src/SprowCoPro.cpp.i

src/SprowCoPro.s: src/SprowCoPro.cpp.s
.PHONY : src/SprowCoPro.s

# target to generate assembly for a file
src/SprowCoPro.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/SprowCoPro.cpp.s
.PHONY : src/SprowCoPro.cpp.s

src/StringUtils.o: src/StringUtils.cpp.o
.PHONY : src/StringUtils.o

# target to build an object file
src/StringUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/StringUtils.cpp.o
.PHONY : src/StringUtils.cpp.o

src/StringUtils.i: src/StringUtils.cpp.i
.PHONY : src/StringUtils.i

# target to preprocess a source file
src/StringUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/StringUtils.cpp.i
.PHONY : src/StringUtils.cpp.i

src/StringUtils.s: src/StringUtils.cpp.s
.PHONY : src/StringUtils.s

# target to generate assembly for a file
src/StringUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/StringUtils.cpp.s
.PHONY : src/StringUtils.cpp.s

src/SysVia.o: src/SysVia.cpp.o
.PHONY : src/SysVia.o

# target to build an object file
src/SysVia.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/SysVia.cpp.o
.PHONY : src/SysVia.cpp.o

src/SysVia.i: src/SysVia.cpp.i
.PHONY : src/SysVia.i

# target to preprocess a source file
src/SysVia.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/SysVia.cpp.i
.PHONY : src/SysVia.cpp.i

src/SysVia.s: src/SysVia.cpp.s
.PHONY : src/SysVia.s

# target to generate assembly for a file
src/SysVia.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/SysVia.cpp.s
.PHONY : src/SysVia.cpp.s

src/TapeControlDialog.o: src/TapeControlDialog.cpp.o
.PHONY : src/TapeControlDialog.o

# target to build an object file
src/TapeControlDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/TapeControlDialog.cpp.o
.PHONY : src/TapeControlDialog.cpp.o

src/TapeControlDialog.i: src/TapeControlDialog.cpp.i
.PHONY : src/TapeControlDialog.i

# target to preprocess a source file
src/TapeControlDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/TapeControlDialog.cpp.i
.PHONY : src/TapeControlDialog.cpp.i

src/TapeControlDialog.s: src/TapeControlDialog.cpp.s
.PHONY : src/TapeControlDialog.s

# target to generate assembly for a file
src/TapeControlDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/TapeControlDialog.cpp.s
.PHONY : src/TapeControlDialog.cpp.s

src/TapeMap.o: src/TapeMap.cpp.o
.PHONY : src/TapeMap.o

# target to build an object file
src/TapeMap.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/TapeMap.cpp.o
.PHONY : src/TapeMap.cpp.o

src/TapeMap.i: src/TapeMap.cpp.i
.PHONY : src/TapeMap.i

# target to preprocess a source file
src/TapeMap.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/TapeMap.cpp.i
.PHONY : src/TapeMap.cpp.i

src/TapeMap.s: src/TapeMap.cpp.s
.PHONY : src/TapeMap.s

# target to generate assembly for a file
src/TapeMap.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/TapeMap.cpp.s
.PHONY : src/TapeMap.cpp.s

src/Teletext.o: src/Teletext.cpp.o
.PHONY : src/Teletext.o

# target to build an object file
src/Teletext.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Teletext.cpp.o
.PHONY : src/Teletext.cpp.o

src/Teletext.i: src/Teletext.cpp.i
.PHONY : src/Teletext.i

# target to preprocess a source file
src/Teletext.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Teletext.cpp.i
.PHONY : src/Teletext.cpp.i

src/Teletext.s: src/Teletext.cpp.s
.PHONY : src/Teletext.s

# target to generate assembly for a file
src/Teletext.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Teletext.cpp.s
.PHONY : src/Teletext.cpp.s

src/Thread.o: src/Thread.cpp.o
.PHONY : src/Thread.o

# target to build an object file
src/Thread.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Thread.cpp.o
.PHONY : src/Thread.cpp.o

src/Thread.i: src/Thread.cpp.i
.PHONY : src/Thread.i

# target to preprocess a source file
src/Thread.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Thread.cpp.i
.PHONY : src/Thread.cpp.i

src/Thread.s: src/Thread.cpp.s
.PHONY : src/Thread.s

# target to generate assembly for a file
src/Thread.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Thread.cpp.s
.PHONY : src/Thread.cpp.s

src/TouchScreen.o: src/TouchScreen.cpp.o
.PHONY : src/TouchScreen.o

# target to build an object file
src/TouchScreen.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/TouchScreen.cpp.o
.PHONY : src/TouchScreen.cpp.o

src/TouchScreen.i: src/TouchScreen.cpp.i
.PHONY : src/TouchScreen.i

# target to preprocess a source file
src/TouchScreen.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/TouchScreen.cpp.i
.PHONY : src/TouchScreen.cpp.i

src/TouchScreen.s: src/TouchScreen.cpp.s
.PHONY : src/TouchScreen.s

# target to generate assembly for a file
src/TouchScreen.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/TouchScreen.cpp.s
.PHONY : src/TouchScreen.cpp.s

src/Tube.o: src/Tube.cpp.o
.PHONY : src/Tube.o

# target to build an object file
src/Tube.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Tube.cpp.o
.PHONY : src/Tube.cpp.o

src/Tube.i: src/Tube.cpp.i
.PHONY : src/Tube.i

# target to preprocess a source file
src/Tube.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Tube.cpp.i
.PHONY : src/Tube.cpp.i

src/Tube.s: src/Tube.cpp.s
.PHONY : src/Tube.s

# target to generate assembly for a file
src/Tube.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Tube.cpp.s
.PHONY : src/Tube.cpp.s

src/Uef.o: src/Uef.cpp.o
.PHONY : src/Uef.o

# target to build an object file
src/Uef.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Uef.cpp.o
.PHONY : src/Uef.cpp.o

src/Uef.i: src/Uef.cpp.i
.PHONY : src/Uef.i

# target to preprocess a source file
src/Uef.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Uef.cpp.i
.PHONY : src/Uef.cpp.i

src/Uef.s: src/Uef.cpp.s
.PHONY : src/Uef.s

# target to generate assembly for a file
src/Uef.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Uef.cpp.s
.PHONY : src/Uef.cpp.s

src/UefState.o: src/UefState.cpp.o
.PHONY : src/UefState.o

# target to build an object file
src/UefState.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/UefState.cpp.o
.PHONY : src/UefState.cpp.o

src/UefState.i: src/UefState.cpp.i
.PHONY : src/UefState.i

# target to preprocess a source file
src/UefState.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/UefState.cpp.i
.PHONY : src/UefState.cpp.i

src/UefState.s: src/UefState.cpp.s
.PHONY : src/UefState.s

# target to generate assembly for a file
src/UefState.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/UefState.cpp.s
.PHONY : src/UefState.cpp.s

src/UserKeyboardDialog.o: src/UserKeyboardDialog.cpp.o
.PHONY : src/UserKeyboardDialog.o

# target to build an object file
src/UserKeyboardDialog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/UserKeyboardDialog.cpp.o
.PHONY : src/UserKeyboardDialog.cpp.o

src/UserKeyboardDialog.i: src/UserKeyboardDialog.cpp.i
.PHONY : src/UserKeyboardDialog.i

# target to preprocess a source file
src/UserKeyboardDialog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/UserKeyboardDialog.cpp.i
.PHONY : src/UserKeyboardDialog.cpp.i

src/UserKeyboardDialog.s: src/UserKeyboardDialog.cpp.s
.PHONY : src/UserKeyboardDialog.s

# target to generate assembly for a file
src/UserKeyboardDialog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/UserKeyboardDialog.cpp.s
.PHONY : src/UserKeyboardDialog.cpp.s

src/UserPortBreakoutBox.o: src/UserPortBreakoutBox.cpp.o
.PHONY : src/UserPortBreakoutBox.o

# target to build an object file
src/UserPortBreakoutBox.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/UserPortBreakoutBox.cpp.o
.PHONY : src/UserPortBreakoutBox.cpp.o

src/UserPortBreakoutBox.i: src/UserPortBreakoutBox.cpp.i
.PHONY : src/UserPortBreakoutBox.i

# target to preprocess a source file
src/UserPortBreakoutBox.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/UserPortBreakoutBox.cpp.i
.PHONY : src/UserPortBreakoutBox.cpp.i

src/UserPortBreakoutBox.s: src/UserPortBreakoutBox.cpp.s
.PHONY : src/UserPortBreakoutBox.s

# target to generate assembly for a file
src/UserPortBreakoutBox.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/UserPortBreakoutBox.cpp.s
.PHONY : src/UserPortBreakoutBox.cpp.s

src/UserPortRTC.o: src/UserPortRTC.cpp.o
.PHONY : src/UserPortRTC.o

# target to build an object file
src/UserPortRTC.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/UserPortRTC.cpp.o
.PHONY : src/UserPortRTC.cpp.o

src/UserPortRTC.i: src/UserPortRTC.cpp.i
.PHONY : src/UserPortRTC.i

# target to preprocess a source file
src/UserPortRTC.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/UserPortRTC.cpp.i
.PHONY : src/UserPortRTC.cpp.i

src/UserPortRTC.s: src/UserPortRTC.cpp.s
.PHONY : src/UserPortRTC.s

# target to generate assembly for a file
src/UserPortRTC.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/UserPortRTC.cpp.s
.PHONY : src/UserPortRTC.cpp.s

src/UserVia.o: src/UserVia.cpp.o
.PHONY : src/UserVia.o

# target to build an object file
src/UserVia.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/UserVia.cpp.o
.PHONY : src/UserVia.cpp.o

src/UserVia.i: src/UserVia.cpp.i
.PHONY : src/UserVia.i

# target to preprocess a source file
src/UserVia.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/UserVia.cpp.i
.PHONY : src/UserVia.cpp.i

src/UserVia.s: src/UserVia.cpp.s
.PHONY : src/UserVia.s

# target to generate assembly for a file
src/UserVia.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/UserVia.cpp.s
.PHONY : src/UserVia.cpp.s

src/Via.o: src/Via.cpp.o
.PHONY : src/Via.o

# target to build an object file
src/Via.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Via.cpp.o
.PHONY : src/Via.cpp.o

src/Via.i: src/Via.cpp.i
.PHONY : src/Via.i

# target to preprocess a source file
src/Via.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Via.cpp.i
.PHONY : src/Via.cpp.i

src/Via.s: src/Via.cpp.s
.PHONY : src/Via.s

# target to generate assembly for a file
src/Via.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Via.cpp.s
.PHONY : src/Via.cpp.s

src/Video.o: src/Video.cpp.o
.PHONY : src/Video.o

# target to build an object file
src/Video.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Video.cpp.o
.PHONY : src/Video.cpp.o

src/Video.i: src/Video.cpp.i
.PHONY : src/Video.i

# target to preprocess a source file
src/Video.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Video.cpp.i
.PHONY : src/Video.cpp.i

src/Video.s: src/Video.cpp.s
.PHONY : src/Video.s

# target to generate assembly for a file
src/Video.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Video.cpp.s
.PHONY : src/Video.cpp.s

src/WindowUtils.o: src/WindowUtils.cpp.o
.PHONY : src/WindowUtils.o

# target to build an object file
src/WindowUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/WindowUtils.cpp.o
.PHONY : src/WindowUtils.cpp.o

src/WindowUtils.i: src/WindowUtils.cpp.i
.PHONY : src/WindowUtils.i

# target to preprocess a source file
src/WindowUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/WindowUtils.cpp.i
.PHONY : src/WindowUtils.cpp.i

src/WindowUtils.s: src/WindowUtils.cpp.s
.PHONY : src/WindowUtils.s

# target to generate assembly for a file
src/WindowUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/WindowUtils.cpp.s
.PHONY : src/WindowUtils.cpp.s

src/Z80.o: src/Z80.cpp.o
.PHONY : src/Z80.o

# target to build an object file
src/Z80.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Z80.cpp.o
.PHONY : src/Z80.cpp.o

src/Z80.i: src/Z80.cpp.i
.PHONY : src/Z80.i

# target to preprocess a source file
src/Z80.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Z80.cpp.i
.PHONY : src/Z80.cpp.i

src/Z80.s: src/Z80.cpp.s
.PHONY : src/Z80.s

# target to generate assembly for a file
src/Z80.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Z80.cpp.s
.PHONY : src/Z80.cpp.s

src/Z80Disassembler.o: src/Z80Disassembler.cpp.o
.PHONY : src/Z80Disassembler.o

# target to build an object file
src/Z80Disassembler.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Z80Disassembler.cpp.o
.PHONY : src/Z80Disassembler.cpp.o

src/Z80Disassembler.i: src/Z80Disassembler.cpp.i
.PHONY : src/Z80Disassembler.i

# target to preprocess a source file
src/Z80Disassembler.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Z80Disassembler.cpp.i
.PHONY : src/Z80Disassembler.cpp.i

src/Z80Disassembler.s: src/Z80Disassembler.cpp.s
.PHONY : src/Z80Disassembler.s

# target to generate assembly for a file
src/Z80Disassembler.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Z80Disassembler.cpp.s
.PHONY : src/Z80Disassembler.cpp.s

src/Z80Support.o: src/Z80Support.cpp.o
.PHONY : src/Z80Support.o

# target to build an object file
src/Z80Support.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Z80Support.cpp.o
.PHONY : src/Z80Support.cpp.o

src/Z80Support.i: src/Z80Support.cpp.i
.PHONY : src/Z80Support.i

# target to preprocess a source file
src/Z80Support.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Z80Support.cpp.i
.PHONY : src/Z80Support.cpp.i

src/Z80Support.s: src/Z80Support.cpp.s
.PHONY : src/Z80Support.s

# target to generate assembly for a file
src/Z80Support.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/Z80Support.cpp.s
.PHONY : src/Z80Support.cpp.s

src/macos/BeebEmPages.o: src/macos/BeebEmPages.mm.o
.PHONY : src/macos/BeebEmPages.o

# target to build an object file
src/macos/BeebEmPages.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/macos/BeebEmPages.mm.o
.PHONY : src/macos/BeebEmPages.mm.o

src/macos/BeebMenu.o: src/macos/BeebMenu.mm.o
.PHONY : src/macos/BeebMenu.o

# target to build an object file
src/macos/BeebMenu.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/macos/BeebMenu.mm.o
.PHONY : src/macos/BeebMenu.mm.o

src/macos/FileDialogMac.o: src/macos/FileDialogMac.mm.o
.PHONY : src/macos/FileDialogMac.o

# target to build an object file
src/macos/FileDialogMac.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/macos/FileDialogMac.mm.o
.PHONY : src/macos/FileDialogMac.mm.o

src/macos/MacPlatform.o: src/macos/MacPlatform.mm.o
.PHONY : src/macos/MacPlatform.o

# target to build an object file
src/macos/MacPlatform.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/macos/MacPlatform.mm.o
.PHONY : src/macos/MacPlatform.mm.o

src/macos/Windows.o: src/macos/Windows.mm.o
.PHONY : src/macos/Windows.o

# target to build an object file
src/macos/Windows.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/macos/Windows.mm.o
.PHONY : src/macos/Windows.mm.o

src/main.o: src/main.mm.o
.PHONY : src/main.o

# target to build an object file
src/main.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/BeebEm.dir/build.make CMakeFiles/BeebEm.dir/src/main.mm.o
.PHONY : src/main.mm.o

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... MetalShaders"
	@echo "... BeebEm"
	@echo "... src/6502core.o"
	@echo "... src/6502core.i"
	@echo "... src/6502core.s"
	@echo "... src/ARMulator/armdis.o"
	@echo "... src/ARMulator/armdis.i"
	@echo "... src/ARMulator/armdis.s"
	@echo "... src/ARMulator/armemu.o"
	@echo "... src/ARMulator/armemu.i"
	@echo "... src/ARMulator/armemu.s"
	@echo "... src/ARMulator/arminit.o"
	@echo "... src/ARMulator/arminit.i"
	@echo "... src/ARMulator/arminit.s"
	@echo "... src/ARMulator/armstubs.o"
	@echo "... src/ARMulator/armstubs.i"
	@echo "... src/ARMulator/armstubs.s"
	@echo "... src/ARMulator/armsupp.o"
	@echo "... src/ARMulator/armsupp.i"
	@echo "... src/ARMulator/armsupp.s"
	@echo "... src/ARMulator/thumbemu.o"
	@echo "... src/ARMulator/thumbemu.i"
	@echo "... src/ARMulator/thumbemu.s"
	@echo "... src/AppDelegate.o"
	@echo "... src/Arm.o"
	@echo "... src/Arm.i"
	@echo "... src/Arm.s"
	@echo "... src/ArmDisassembler.o"
	@echo "... src/ArmDisassembler.i"
	@echo "... src/ArmDisassembler.s"
	@echo "... src/AtoDConv.o"
	@echo "... src/AtoDConv.i"
	@echo "... src/AtoDConv.s"
	@echo "... src/AviWriter.o"
	@echo "... src/AviWriter.i"
	@echo "... src/AviWriter.s"
	@echo "... src/Bcd.o"
	@echo "... src/Bcd.i"
	@echo "... src/Bcd.s"
	@echo "... src/BeebMem.o"
	@echo "... src/BeebMem.i"
	@echo "... src/BeebMem.s"
	@echo "... src/BeebMetalView.o"
	@echo "... src/BeebRenderer.o"
	@echo "... src/BeebWin.o"
	@echo "... src/BeebWin.i"
	@echo "... src/BeebWin.s"
	@echo "... src/BeebWinDx.o"
	@echo "... src/BeebWinDx.i"
	@echo "... src/BeebWinDx.s"
	@echo "... src/BeebWinIo.o"
	@echo "... src/BeebWinIo.i"
	@echo "... src/BeebWinIo.s"
	@echo "... src/BeebWinPrefs.o"
	@echo "... src/BeebWinPrefs.i"
	@echo "... src/BeebWinPrefs.s"
	@echo "... src/BeebWinSpeech.o"
	@echo "... src/BeebWinSpeech.i"
	@echo "... src/BeebWinSpeech.s"
	@echo "... src/ComboBox.o"
	@echo "... src/ComboBox.i"
	@echo "... src/ComboBox.s"
	@echo "... src/CoreAudioStreamer.o"
	@echo "... src/Csw.o"
	@echo "... src/Csw.i"
	@echo "... src/Csw.s"
	@echo "... src/Debug.o"
	@echo "... src/Debug.i"
	@echo "... src/Debug.s"
	@echo "... src/DebugTrace.o"
	@echo "... src/DebugTrace.i"
	@echo "... src/DebugTrace.s"
	@echo "... src/Dialog.o"
	@echo "... src/Dialog.i"
	@echo "... src/Dialog.s"
	@echo "... src/Disc1770.o"
	@echo "... src/Disc1770.i"
	@echo "... src/Disc1770.s"
	@echo "... src/Disc8271.o"
	@echo "... src/Disc8271.i"
	@echo "... src/Disc8271.s"
	@echo "... src/DiscEdit.o"
	@echo "... src/DiscEdit.i"
	@echo "... src/DiscEdit.s"
	@echo "... src/DiscInfo.o"
	@echo "... src/DiscInfo.i"
	@echo "... src/DiscInfo.s"
	@echo "... src/Econet.o"
	@echo "... src/Econet.i"
	@echo "... src/Econet.s"
	@echo "... src/Ext1770.o"
	@echo "... src/Ext1770.i"
	@echo "... src/Ext1770.s"
	@echo "... src/FileType.o"
	@echo "... src/FileType.i"
	@echo "... src/FileType.s"
	@echo "... src/FileUtils.o"
	@echo "... src/FileUtils.i"
	@echo "... src/FileUtils.s"
	@echo "... src/Hardware/Acorn1770/Acorn.o"
	@echo "... src/Hardware/Acorn1770/Acorn.i"
	@echo "... src/Hardware/Acorn1770/Acorn.s"
	@echo "... src/Hardware/OpusDDOS/Opus.o"
	@echo "... src/Hardware/OpusDDOS/Opus.i"
	@echo "... src/Hardware/OpusDDOS/Opus.s"
	@echo "... src/Hardware/Watford/Watford.o"
	@echo "... src/Hardware/Watford/Watford.i"
	@echo "... src/Hardware/Watford/Watford.s"
	@echo "... src/IC32Latch.o"
	@echo "... src/IC32Latch.i"
	@echo "... src/IC32Latch.s"
	@echo "... src/IP232.o"
	@echo "... src/IP232.i"
	@echo "... src/IP232.s"
	@echo "... src/Ide.o"
	@echo "... src/Ide.i"
	@echo "... src/Ide.s"
	@echo "... src/JoystickController.o"
	@echo "... src/JoystickController.i"
	@echo "... src/JoystickController.s"
	@echo "... src/JoystickDialog.o"
	@echo "... src/JoystickDialog.i"
	@echo "... src/JoystickDialog.s"
	@echo "... src/JoystickOptions.o"
	@echo "... src/JoystickOptions.i"
	@echo "... src/JoystickOptions.s"
	@echo "... src/KeyMap.o"
	@echo "... src/KeyMap.i"
	@echo "... src/KeyMap.s"
	@echo "... src/KeyboardLinksDialog.o"
	@echo "... src/KeyboardLinksDialog.i"
	@echo "... src/KeyboardLinksDialog.s"
	@echo "... src/ListView.o"
	@echo "... src/ListView.i"
	@echo "... src/ListView.s"
	@echo "... src/Log.o"
	@echo "... src/Log.i"
	@echo "... src/Log.s"
	@echo "... src/Master512CoPro.o"
	@echo "... src/Master512CoPro.i"
	@echo "... src/Master512CoPro.s"
	@echo "... src/Model.o"
	@echo "... src/Model.i"
	@echo "... src/Model.s"
	@echo "... src/Music5000.o"
	@echo "... src/Music5000.i"
	@echo "... src/Music5000.s"
	@echo "... src/PALRom.o"
	@echo "... src/PALRom.i"
	@echo "... src/PALRom.s"
	@echo "... src/Preferences.o"
	@echo "... src/Preferences.i"
	@echo "... src/Preferences.s"
	@echo "... src/RingBuffer.o"
	@echo "... src/RingBuffer.i"
	@echo "... src/RingBuffer.s"
	@echo "... src/RomConfigFile.o"
	@echo "... src/RomConfigFile.i"
	@echo "... src/RomConfigFile.s"
	@echo "... src/Rtc.o"
	@echo "... src/Rtc.i"
	@echo "... src/Rtc.s"
	@echo "... src/Sasi.o"
	@echo "... src/Sasi.i"
	@echo "... src/Sasi.s"
	@echo "... src/Scsi.o"
	@echo "... src/Scsi.i"
	@echo "... src/Scsi.s"
	@echo "... src/Serial.o"
	@echo "... src/Serial.i"
	@echo "... src/Serial.s"
	@echo "... src/SerialPort.o"
	@echo "... src/SerialPort.i"
	@echo "... src/SerialPort.s"
	@echo "... src/Socket.o"
	@echo "... src/Socket.i"
	@echo "... src/Socket.s"
	@echo "... src/Sound.o"
	@echo "... src/Sound.i"
	@echo "... src/Sound.s"
	@echo "... src/SoundStreamer.o"
	@echo "... src/SoundStreamer.i"
	@echo "... src/SoundStreamer.s"
	@echo "... src/Speech.o"
	@echo "... src/Speech.i"
	@echo "... src/Speech.s"
	@echo "... src/SprowCoPro.o"
	@echo "... src/SprowCoPro.i"
	@echo "... src/SprowCoPro.s"
	@echo "... src/StringUtils.o"
	@echo "... src/StringUtils.i"
	@echo "... src/StringUtils.s"
	@echo "... src/SysVia.o"
	@echo "... src/SysVia.i"
	@echo "... src/SysVia.s"
	@echo "... src/TapeControlDialog.o"
	@echo "... src/TapeControlDialog.i"
	@echo "... src/TapeControlDialog.s"
	@echo "... src/TapeMap.o"
	@echo "... src/TapeMap.i"
	@echo "... src/TapeMap.s"
	@echo "... src/Teletext.o"
	@echo "... src/Teletext.i"
	@echo "... src/Teletext.s"
	@echo "... src/Thread.o"
	@echo "... src/Thread.i"
	@echo "... src/Thread.s"
	@echo "... src/TouchScreen.o"
	@echo "... src/TouchScreen.i"
	@echo "... src/TouchScreen.s"
	@echo "... src/Tube.o"
	@echo "... src/Tube.i"
	@echo "... src/Tube.s"
	@echo "... src/Uef.o"
	@echo "... src/Uef.i"
	@echo "... src/Uef.s"
	@echo "... src/UefState.o"
	@echo "... src/UefState.i"
	@echo "... src/UefState.s"
	@echo "... src/UserKeyboardDialog.o"
	@echo "... src/UserKeyboardDialog.i"
	@echo "... src/UserKeyboardDialog.s"
	@echo "... src/UserPortBreakoutBox.o"
	@echo "... src/UserPortBreakoutBox.i"
	@echo "... src/UserPortBreakoutBox.s"
	@echo "... src/UserPortRTC.o"
	@echo "... src/UserPortRTC.i"
	@echo "... src/UserPortRTC.s"
	@echo "... src/UserVia.o"
	@echo "... src/UserVia.i"
	@echo "... src/UserVia.s"
	@echo "... src/Via.o"
	@echo "... src/Via.i"
	@echo "... src/Via.s"
	@echo "... src/Video.o"
	@echo "... src/Video.i"
	@echo "... src/Video.s"
	@echo "... src/WindowUtils.o"
	@echo "... src/WindowUtils.i"
	@echo "... src/WindowUtils.s"
	@echo "... src/Z80.o"
	@echo "... src/Z80.i"
	@echo "... src/Z80.s"
	@echo "... src/Z80Disassembler.o"
	@echo "... src/Z80Disassembler.i"
	@echo "... src/Z80Disassembler.s"
	@echo "... src/Z80Support.o"
	@echo "... src/Z80Support.i"
	@echo "... src/Z80Support.s"
	@echo "... src/macos/BeebEmPages.o"
	@echo "... src/macos/BeebMenu.o"
	@echo "... src/macos/FileDialogMac.o"
	@echo "... src/macos/MacPlatform.o"
	@echo "... src/macos/Windows.o"
	@echo "... src/main.o"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

